services:
  3xui-shopbot:
    build: .
    restart: unless-stopped
    ports:
      - '1488:1488'
    volumes:
      - .:/app/project
      - shopbot-db:/app/project/data
      - ./ssh-keys:/root/.ssh
    container_name: 3xui-shopbot
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SHOPBOT_DB_PATH=/app/project/data/users.db
      - TZ=Europe/Moscow
      - RKN_API_HOST=host.docker.internal
      - AUTO_START_BOT=true

volumes:
  shopbot-db:
